### ISSUE TITLE
Modular Machinery

### ISSUE THREAD

**Issue by CrazyKiller3000** [Project-Interactions/Interactions#34]
I can't progress in the modpack anymore because of Modular Machinery. There is an opengl error when trying to access structure preview and there are no instructions on how to use the multiblock builder that you need for a quest along with modular machinery.

**Comment by CrazyKiller3000** [comment]
when I right click using the multiblock builder on the magnetizer controller I get this crash report:
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: ink/ikx/mmce/common/utils/StructureIngredient
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:826)
Caused by: java.lang.NoClassDefFoundError: ink/ikx/mmce/common/utils/StructureIngredient
    at ink.ikx.mmce.core.AssemblyEventHandler.assemblyBefore(AssemblyEventHandler.java:125)
    at ink.ikx.mmce.core.AssemblyEventHandler.onRightClickBlock(AssemblyEventHandler.java:76)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3742_AssemblyEventHandler_onRightClickBlock_RightClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onRightClickBlock(MixinForgeHooks.java:1137)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:433)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

**Comment by mczph** [comment]
> when I right click using the multiblock builder on the magnetizer controller I get this crash report:
> Description: Error executing task
> 
> java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: ink/ikx/mmce/common/utils/StructureIngredient
>     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>     at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>     at net.minecraft.util.Util.runTask(Util.java:531)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
>     at java.lang.Thread.run(Thread.java:826)
> Caused by: java.lang.NoClassDefFoundError: ink/ikx/mmce/common/utils/StructureIngredient
>     at ink.ikx.mmce.core.AssemblyEventHandler.assemblyBefore(AssemblyEventHandler.java:125)
>     at ink.ikx.mmce.core.AssemblyEventHandler.onRightClickBlock(AssemblyEventHandler.java:76)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3742_AssemblyEventHandler_onRightClickBlock_RightClickBlock.invoke(.dynamic)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
>     at net.minecraftforge.common.ForgeHooks.onRightClickBlock(MixinForgeHooks.java:1137)
>     at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:433)
>     at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
>     at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at net.minecraft.util.Util.runTask(Util.java:529)
>     ... 5 more
> 

This unexpected behavior is reported by a few players before.I'm not completely clear about the problem,but a possible solution is to change your java version(like 382 or newer).(also I'd like to ask which java version are you using?)

**Comment by CrazyKiller3000** [comment]
I'm using openj9 jre 8.0.402.6.

**Comment by mczph** [comment]
> I'm using openj9 jre 8.0.402.6.

try not using openj9

**Comment by CrazyKiller3000** [comment]
Ok, I'm going to try EclipseAdoptium, and if that doesn't work, I'll try the normal version from Java.com

**Comment by CrazyKiller3000** [comment]
It seems that openj9 was the problem, eclipse works. Thank you, I didn't even consider changing the java version.
